server:
  #    port: 8800
  port: 8080
spring:
  application:
    name: pets
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/english_read?serverTimezone=GMT%2b8
    username: root
    password: qianjin4
    #        password: Root@425700
    type: com.alibaba.druid.pool.DruidDataSource

    #连接池属性
    #springboot默认不注入这些属性，需要配置druid配置类来注入
    initialSize: 5
    minIdle: 5
    maxActive: 25
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    static-path-pattern: /**
mybatis:  #mybatis映射文件通配
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#    分页器配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
